services:

  keycloak:
    image: keycloak/keycloak:26.0
    container_name: keycloak
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: vivo
      KC_BOOTSTRAP_ADMIN_PASSWORD: edutech
      KEYCLOAK_DATABASE_VENDOR: dev-file
    ports:
      - 9090:8080
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    command: start-dev --import-realm

  rabbitmq:
    image: rabbitmq:4.0.5-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: vivo
      RABBITMQ_DEFAULT_PASS: edutech
    ports:
      - 5672:5672
      - 15672:15672
